service: bubbler-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-wines
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 2
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # serverless-webpack configuration
  # Enable auto-packing of external modules
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-2

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${self:custom.tableName}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ WinesTable, Arn ]

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /wines
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: create.main
    events:
      - http:
          path: wines
          method: post
          cors: true
          authorizer: aws_iam
  # Defines an HTTP API endpoint that calls the main function in get.js
  # - path: url path is /wines/{id}
  # - method: GET request
  get:
    handler: get.main
    events:
      - http:
          path: wines/{id}
          method: get
          cors: true
          authorizer: aws_iam
  # Defines an HTTP API endpoint that calls the main function in list.js
  # - path: url path is /wines
  # - method: GET request
  list:
      handler: list.main
      events:
        - http:
            path: wines
            method: get
            cors: true
            authorizer: aws_iam
  # Defines an HTTP API endpoint that calls the main function in update.js
  # - path: url path is /wines/{id}
  # - method: PUT request
  update:
    handler: update.main
    events:
      - http:
          path: wines/{id}
          method: put
          cors: true
          authorizer: aws_iam
  # Defines an HTTP API endpoint that calls the main function in delete.js
  # - path: url path is /wines/{id}
  # - method: DELETE request
  delete:
    handler: delete.main
    events:
      - http:
          path: wines/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  # Defines an HTTP API endpoint that calls the main function in getSystembolagetData.js
  # - path: url path is /systembolaget
  # - method: GET request
  getSystembolagetData:
    handler: getSystembolagetData.main
    events:
      - http:
          path: systembolaget
          method: get
          cors: true
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}


